[package]
name = "chapter4"
version = "0.1.0"
edition = "2021"

[[src]]
name = "ownership"
test = false
bench = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]